name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CLM_RUN
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade cloud-ml-sdk cloud-ml-common
          pip install -r requirements.txt
          pip install cml
          cml publish -c "Model training workflow completed successfully!"
          python train.py
          echo "##Modale Matrix" >> report.md 
          cat metrics.txt >> report.md 
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cml-send-comment report.md
